version: '3'

services:
  movie-app:
    build: .
    container_name: movie-processor
    ports:
      - "8001:8001"
    volumes:
      - ./temp:/app/temp
      - ./output:/app/output
    restart: unless-stopped
    environment:
      - TZ=Asia/Kolkata
